server:
  port: 8787
  context-path: /ms-companies-fallback
spring:
  application:
    name: ms-companies-fallback

  config:
    import: optional:configserver:http://localhost:8888
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
